<a href="https://colab.research.google.com/github/EddyGiusepe/Pytorch/blob/main/1_Pytorch_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h2 align="center">Pytorch: Introdução</h2>

Data Scientist: Dr.Eddy Giusepe Chirinos Isidro

Em scripts anteriores estudamos os elementos fundamentais das REDES NEURAIS: o `Perceptron`, o algoritmo de `descenso por gradiente`, o `Perceptron Multicapa (MLP)`, etc. Agora, neste script estudaremos e aprenderemos a trabalhar com um dos Frameworks de Redes Neurais mais utilizados hoje em dia: [Pytorch](https://pytorch.org/). 



![](https://tempodeinovacao.com.br/wp-content/uploads/2020/08/1_t6hCM90evdnlPw4l9VK3AQ.png)

In [1]:
import torch

# O que é Pytorch?



`Pytorch` é um Framework de Redes Neurais, um conjunto de bibliotecas e ferramentas que nos farão a vida mais fácil à hora de desenhar, treinar e colocar em produção nossos modelos de Deep Learning. Uma forma simples de entender o que é Pytorch é da seguinte maneira:

$$ Pytorch = Numpy + Autograd + GPU $$

Vamos ver que significa cada um destes termos:

# NumPy

Talvez a característica mais relevante de `Pytorch` é a sua facilidade de uso. Isto é devido porque segue uma interface muito similar à de `NumPy`. Então, como já sabemos trabalhar com esta biblioteca não teremos muitos problemas de aprender a trabalhar com Pytorch.


Da mesma maneira que em `NumPy` o objeto principal é o `ndarray`, em `Pytorch` o objeto principal é o `Tensor`. Podemos definir um Tensor de maneira similar a como a como definimos um array, incluso podemos inicializar Tensores a partir de arrays.

In [2]:
# matriz de ceros, 5 filas y 3 columnas
# 2D
x = torch.zeros(5, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [5]:
# tensor con valores aleatorios
# Tensor tri-Dimensional
x = torch.randn(5, 3, 2) # Teriamos 5 matrizes de 3 filas e 2 colunas 
x

tensor([[[ 0.2193,  1.3796],
         [ 1.1913,  0.2060],
         [-1.2729, -0.6872]],

        [[ 0.8077, -0.0191],
         [-0.3017, -0.6460],
         [ 0.3773, -1.0822]],

        [[-0.7123,  0.1289],
         [ 0.1715,  0.3432],
         [-1.0675,  0.6113]],

        [[ 0.0410,  1.3531],
         [ 0.6538,  0.0632],
         [ 0.3122,  0.6018]],

        [[-0.4985,  0.9556],
         [ 0.9557,  0.2680],
         [ 1.9618, -0.0818]]])

In [12]:
# Tensor a partir de lista 

x_lista = [[1, 2, 3],[4, 5, 6]]
x_lista, type(x_lista)



([[1, 2, 3], [4, 5, 6]], list)

In [13]:
x_tensor = torch.tensor([[1, 2, 3],[4, 5, 6]])
x_tensor, type(x_tensor)

(tensor([[1, 2, 3],
         [4, 5, 6]]), torch.Tensor)

In [15]:
import numpy as np

# tensor a partir de array

a = np.array([[1, 2, 3],[4, 5, 6]])
a, type(a)

(array([[1, 2, 3],
        [4, 5, 6]]), numpy.ndarray)

In [18]:
x = torch.from_numpy(a)
x, type(x)

(tensor([[1, 2, 3],
         [4, 5, 6]]), torch.Tensor)

Podemos observar que praticamente todos os conceitos que já conhecemos de NumPy podem ser aplicados em Pytorch. Isto inclui operações `aritméticas`, `indexado` e `fatiado`, `iteração`, `vetorização` e [broadcating](https://machinelearningmastery.com/broadcasting-with-numpy-arrays/#:~:text=Broadcasting%20solves%20the%20problem%20of,different%20shapes%20during%20arithmetic%20operations.).