<a href="https://colab.research.google.com/github/EddyGiusepe/Pytorch/blob/main/1_Pytorch_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h2 align="center">Pytorch: Introdução</h2>

Data Scientist: Dr.Eddy Giusepe Chirinos Isidro

Em scripts anteriores estudamos os elementos fundamentais das REDES NEURAIS: o `Perceptron`, o algoritmo de `descenso por gradiente`, o `Perceptron Multicapa (MLP)`, etc. Agora, neste script estudaremos e aprenderemos a trabalhar com um dos Frameworks de Redes Neurais mais utilizados hoje em dia: [Pytorch](https://pytorch.org/). 



![](https://tempodeinovacao.com.br/wp-content/uploads/2020/08/1_t6hCM90evdnlPw4l9VK3AQ.png)

In [ ]:
import torch

# O que é Pytorch?



`Pytorch` é um Framework de Redes Neurais, um conjunto de bibliotecas e ferramentas que nos farão a vida mais fácil à hora de desenhar, treinar e colocar em produção nossos modelos de Deep Learning. Uma forma simples de entender o que é Pytorch é da seguinte maneira:

$$ Pytorch = Numpy + Autograd + GPU $$

Vamos ver que significa cada um destes termos:

# NumPy

Talvez a característica mais relevante de `Pytorch` é a sua facilidade de uso. Isto é devido porque segue uma interface muito similar à de `NumPy`. Então, como já sabemos trabalhar com esta biblioteca não teremos muitos problemas de aprender a trabalhar com Pytorch.


Da mesma maneira que em `NumPy` o objeto principal é o `ndarray`, em `Pytorch` o objeto principal é o `Tensor`. Podemos definir um Tensor de maneira similar a como a como definimos um array, incluso podemos inicializar Tensores a partir de arrays.

In [ ]:
# matriz de ceros, 5 filas y 3 columnas
# 2D
x = torch.zeros(5, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# tensor con valores aleatorios
# Tensor tri-Dimensional
x = torch.randn(5, 3, 2) # Teriamos 5 matrizes de 3 filas e 2 colunas 
x

tensor([[[ 0.7454, -0.4358],
         [ 1.2365,  0.2008],
         [-1.6090, -0.3643]],

        [[-1.1939,  1.1576],
         [ 0.5404, -1.1550],
         [ 1.6152,  0.4150]],

        [[-0.9192, -0.0813],
         [-2.0401, -0.6476],
         [ 1.6316, -0.6177]],

        [[-0.1522,  0.4992],
         [ 0.6662,  0.3713],
         [-0.4244, -1.2104]],

        [[ 0.3213,  1.2219],
         [ 0.1201, -0.1264],
         [-0.9218, -0.3413]]])

In [ ]:
# Tensor a partir de lista 

x_lista = [[1, 2, 3],[4, 5, 6]]
x_lista, type(x_lista)



([[1, 2, 3], [4, 5, 6]], list)

In [ ]:
x_tensor = torch.tensor([[1, 2, 3],[4, 5, 6]])
x_tensor, type(x_tensor)

(tensor([[1, 2, 3],
         [4, 5, 6]]), torch.Tensor)

In [ ]:
import numpy as np

# tensor a partir de array

a = np.array([[1, 2, 3],[4, 5, 6]])
a, type(a)

(array([[1, 2, 3],
        [4, 5, 6]]), numpy.ndarray)

In [ ]:
x = torch.from_numpy(a)
x, type(x)

(tensor([[1, 2, 3],
         [4, 5, 6]]), torch.Tensor)

Podemos observar que praticamente todos os conceitos que já conhecemos de NumPy podem ser aplicados em Pytorch. Isto inclui operações `aritméticas`, `indexado` e `fatiado`, `iteração`, `vetorização` e [broadcating](https://machinelearningmastery.com/broadcasting-with-numpy-arrays/#:~:text=Broadcasting%20solves%20the%20problem%20of,different%20shapes%20during%20arithmetic%20operations.).

In [ ]:
# Operações

x = torch.randn(3, 3)
y = torch.randn(3, 3)

print(x)
print("")
print(y)

tensor([[-0.9130,  0.2711,  0.4142],
        [-1.4123,  0.0282,  0.3951],
        [ 0.7062,  0.6292,  1.8321]])

tensor([[-1.2193, -1.2867, -1.3751],
        [ 0.6877,  0.9321, -0.3973],
        [ 1.2168, -1.0941, -2.1025]])


In [ ]:
x + y

tensor([[-2.1322, -1.0156, -0.9609],
        [-0.7246,  0.9603, -0.0023],
        [ 1.9229, -0.4649, -0.2704]])

In [ ]:
# Outro exemplo 
x_tensor = torch.tensor([[1, 2, 3],[4, 5, 6], [0, -1, -2]])
print(x_tensor)
print("")
y_tensor = torch.tensor([[-1, -2, -3],[4, 5, 6], [0, -1, -2]])
print(y_tensor)
print("")
x_tensor + y_tensor

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 0, -1, -2]])

tensor([[-1, -2, -3],
        [ 4,  5,  6],
        [ 0, -1, -2]])



tensor([[ 0,  0,  0],
        [ 8, 10, 12],
        [ 0, -2, -4]])

In [ ]:
# indexado

# primera fila

x[0]

tensor([-0.9130,  0.2711,  0.4142])

In [ ]:
x_tensor[0]

tensor([1, 2, 3])

In [ ]:
# primera fila, primera columna

x[0, 0]

tensor(-0.9130)

In [ ]:
x_tensor[0, 0]

tensor(1)

In [ ]:
# Primeira linha

x[0, :]

tensor([-0.9130,  0.2711,  0.4142])

In [ ]:
x_tensor[0, :]

tensor([1, 2, 3])

In [ ]:
# Primera coluna

x_tensor[:, 0]

tensor([1, 4, 0])

<font color="orange">Fatiado</font>

In [ ]:
# Fatiado

x[:-1, 1:]

tensor([[0.2711, 0.4142],
        [0.0282, 0.3951]])

In [ ]:
x_tensor[: -1, 1:]

tensor([[2, 3],
        [5, 6]])

In [ ]:
x_tensor[:2, :2]

tensor([[1, 2],
        [4, 5]])

In [ ]:
x_tensor[1:3, 1:3]

tensor([[ 5,  6],
        [-1, -2]])

In [ ]:
x_tensor[1:3, 1:3]

tensor([[ 5,  6],
        [-1, -2]])

<font color="orange">Uma funcionalidade importante do objeto `Tensor` que usaremos muito é mudar a sua forma. Isto é possível com a função `view`.</font>

In [ ]:
x_tensor.shape

torch.Size([3, 3])

In [ ]:
# Adicionamos uma dimensão extra

x_tensor.view(1, 3, 3)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 0, -1, -2]]])

In [ ]:
x_tensor.view(1, 3, 3).shape # 3D

torch.Size([1, 3, 3])

In [ ]:
# Esticamos em apenas uma Dimensão

x_tensor.view(9) # 1D

tensor([ 1,  2,  3,  4,  5,  6,  0, -1, -2])

In [ ]:
x_tensor.view(9).shape

torch.Size([9])