<a href="https://colab.research.google.com/github/EddyGiusepe/Pytorch/blob/main/1_Pytorch_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h2 align="center">Pytorch: Introdução</h2>

Data Scientist: Dr.Eddy Giusepe Chirinos Isidro

Em scripts anteriores estudamos os elementos fundamentais das REDES NEURAIS: o `Perceptron`, o algoritmo de `descenso por gradiente`, o `Perceptron Multicapa (MLP)`, etc. Agora, neste script estudaremos e aprenderemos a trabalhar com um dos Frameworks de Redes Neurais mais utilizados hoje em dia: [Pytorch](https://pytorch.org/). 



![](https://tempodeinovacao.com.br/wp-content/uploads/2020/08/1_t6hCM90evdnlPw4l9VK3AQ.png)

In [1]:
import torch

# O que é Pytorch?



`Pytorch` é um Framework de Redes Neurais, um conjunto de bibliotecas e ferramentas que nos farão a vida mais fácil à hora de desenhar, treinar e colocar em produção nossos modelos de Deep Learning. Uma forma simples de entender o que é Pytorch é da seguinte maneira:

$$ Pytorch = Numpy + Autograd + GPU $$

Vamos ver que significa cada um destes termos:

# NumPy

Talvez a característica mais relevante de `Pytorch` é a sua facilidade de uso. Isto é devido porque segue uma interface muito similar à de `NumPy`. Então, como já sabemos trabalhar com esta biblioteca não teremos muitos problemas de aprender a trabalhar com Pytorch.


Da mesma maneira que em `NumPy` o objeto principal é o `ndarray`, em `Pytorch` o objeto principal é o `Tensor`. Podemos definir um Tensor de maneira similar a como a como definimos um array, incluso podemos inicializar Tensores a partir de arrays.

In [2]:
# matriz de ceros, 5 filas y 3 columnas
# 2D
x = torch.zeros(5, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [3]:
# tensor con valores aleatorios
# Tensor tri-Dimensional
x = torch.randn(5, 3, 2) # Teriamos 5 matrizes de 3 filas e 2 colunas 
x

tensor([[[-0.6597,  0.2248],
         [ 1.0796,  0.9027],
         [ 0.3682, -0.4360]],

        [[ 0.0092, -1.3949],
         [ 0.9494,  1.3405],
         [-0.8748,  1.5451]],

        [[-1.4121, -0.9932],
         [ 0.0373, -2.0330],
         [ 0.2383,  0.2961]],

        [[ 0.2557, -1.8095],
         [-0.1636,  1.2320],
         [-0.2165,  0.1569]],

        [[-1.0532,  0.4663],
         [ 0.0642,  1.5731],
         [-1.9476, -0.6653]]])

In [4]:
# Tensor a partir de lista 

x_lista = [[1, 2, 3],[4, 5, 6]]
x_lista, type(x_lista)



([[1, 2, 3], [4, 5, 6]], list)

In [5]:
x_tensor = torch.tensor([[1, 2, 3],[4, 5, 6]])
x_tensor, type(x_tensor)

(tensor([[1, 2, 3],
         [4, 5, 6]]), torch.Tensor)

In [6]:
import numpy as np

# tensor a partir de array

a = np.array([[1, 2, 3],[4, 5, 6]])
a, type(a)

(array([[1, 2, 3],
        [4, 5, 6]]), numpy.ndarray)

In [7]:
x = torch.from_numpy(a)
x, type(x)

(tensor([[1, 2, 3],
         [4, 5, 6]]), torch.Tensor)

Podemos observar que praticamente todos os conceitos que já conhecemos de NumPy podem ser aplicados em Pytorch. Isto inclui operações `aritméticas`, `indexado` e `fatiado`, `iteração`, `vetorização` e [broadcating](https://machinelearningmastery.com/broadcasting-with-numpy-arrays/#:~:text=Broadcasting%20solves%20the%20problem%20of,different%20shapes%20during%20arithmetic%20operations.).

In [8]:
# Operações

x = torch.randn(3, 3)
y = torch.randn(3, 3)

print(x)
print("")
print(y)

tensor([[-0.7162, -0.3992,  1.2655],
        [-1.4169,  0.2327,  1.2249],
        [-1.2644, -0.1551,  0.0178]])

tensor([[ 0.1310,  0.9698, -0.4284],
        [ 0.7934, -0.1438, -0.8942],
        [-1.3389, -0.1942,  0.6170]])


In [9]:
x + y

tensor([[-0.5852,  0.5706,  0.8370],
        [-0.6235,  0.0889,  0.3307],
        [-2.6033, -0.3493,  0.6348]])

In [10]:
# Outro exemplo 
x_tensor = torch.tensor([[1, 2, 3],[4, 5, 6], [0, -1, -2]])
print(x_tensor)
print("")
y_tensor = torch.tensor([[-1, -2, -3],[4, 5, 6], [0, -1, -2]])
print(y_tensor)
print("")
x_tensor + y_tensor

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 0, -1, -2]])

tensor([[-1, -2, -3],
        [ 4,  5,  6],
        [ 0, -1, -2]])



tensor([[ 0,  0,  0],
        [ 8, 10, 12],
        [ 0, -2, -4]])

In [11]:
# indexado

# primera fila

x[0]

tensor([-0.7162, -0.3992,  1.2655])

In [12]:
x_tensor[0]

tensor([1, 2, 3])

In [13]:
# primera fila, primera columna

x[0, 0]

tensor(-0.7162)

In [14]:
x_tensor[0, 0]

tensor(1)

In [15]:
# Primeira linha

x[0, :]

tensor([-0.7162, -0.3992,  1.2655])

In [16]:
x_tensor[0, :]

tensor([1, 2, 3])

In [17]:
# Primera coluna

x_tensor[:, 0]

tensor([1, 4, 0])

<font color="orange">Fatiado</font>

In [18]:
# Fatiado

x[:-1, 1:]

tensor([[-0.3992,  1.2655],
        [ 0.2327,  1.2249]])

In [19]:
x_tensor[: -1, 1:]

tensor([[2, 3],
        [5, 6]])

In [20]:
x_tensor[:2, :2]

tensor([[1, 2],
        [4, 5]])

In [21]:
x_tensor[1:3, 1:3]

tensor([[ 5,  6],
        [-1, -2]])

In [22]:
x_tensor[1:3, 1:3]

tensor([[ 5,  6],
        [-1, -2]])

<font color="orange">Uma funcionalidade importante do objeto `Tensor` que usaremos muito é mudar a sua forma. Isto é possível com a função `view`.</font>

In [23]:
x_tensor.shape

torch.Size([3, 3])

In [29]:
# 2D
x_tensor 

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 0, -1, -2]])

In [30]:
# Adicionamos uma dimensão extra
# Agora de 3D
x_tensor.view(1, 3, 3)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 0, -1, -2]]])

In [32]:
x_tensor.view(1, 3, 3).shape # 3D

torch.Size([1, 3, 3])

In [33]:
# Esticamos em apenas uma Dimensão
# Nota que os elementos estão ai 
x_tensor.view(9) # 1D

tensor([ 1,  2,  3,  4,  5,  6,  0, -1, -2])

In [34]:
x_tensor.view(9).shape

torch.Size([9])

In [35]:
# Usamos -1 para fornecer todos os valores restantes a uma dimensão

x_tensor.view(-1)

tensor([ 1,  2,  3,  4,  5,  6,  0, -1, -2])

In [36]:
x_tensor.view(-1).shape

torch.Size([9])

<font color="orange">Podemos transformar um `Tensor` em um array com a função `NumPy`.</font>

In [37]:
x_tensor # Isto é um TENSOR

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 0, -1, -2]])

In [38]:
x_tensor.numpy() # Isto é um ARRAY NumPy

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0, -1, -2]])

<font color="orange">Como podemos observar, um TENSOR de PYTORCH é muito similar a um ARRAY de NUMPY. Para mais detalhes e exemplos: [Ver Pytorch](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py)</font>

# Autograd

Como temos visto acima, `Pytorch` é muito similar a `NumPy`. No entanto a funcionalidade de Pytorch vai muito além de uma estrutura de Dados eficiente com a que podemos fazer operações mais complexas (para isso já não é suficiente NumPy). A funcionalidade mais importante que Pytorch adiciona é conhecida como <font color="yellow">autograd</font>, a qual nos proporciona a possibilidade de `calcular DERIVADAS` de maneira automática com respeito a qualquer Tensor. Isto dá a Pytorch um grande potencial para desenhar REDES NEURAIS complexas e treiná-las utilizando algoritmos de gradientes sem ter que calcular todas as derivadas manualmente (tal como foi feito em outros Scripts deste repositório). Para levar em ação estas operações, `Pytorch` vai construindo de maneira dinâmica um `GRAFO COMPUTACIONAL`. Cada vez que aplicamos uma operação sobre um ou vários Tensores, estos se adicionam ao Grafo Computacional junto à operação em concreto. Desta maneira, se queremos calcular a derivada de qualquer valor com respeito a qualquer tensor, simplesmente temos que aplicar o algoritmo de <font color="orange">backpropagation</font> (que não é mais que a REGRA DA CADEIA da DERIVADA) no Grafo. 

Vejamos um exemplo:

In [51]:
x = torch.tensor(1., requires_grad=True)
y = torch.tensor(2., requires_grad=True)
p = x + y

z = torch.tensor(3., requires_grad=True)
g = p * z

Na célula anterior definimos três Tensores: $x$, $y$ e $z$. Em primeiro lugar, para poder calcular derivadas com respeito a estes Tensores necessitamos colocar a propriedade `requires_grad` a `True`. Agora, podemos calcular o Tensor intermédio $p$ como $p = x  + y$ e logo usamos este valor para calcular o resultado final $g$ como $g = p*z$. Cada vez que aplicamos uma operação sobre um Tensor que tem a sua propriedade `requires_grad` a `True`, `Pytorch` irá construindo o `GRAFO COMPUTACIONAL`. 


O grafo teria a seguinte forma:

![](https://www.tutorialspoint.com/python_deep_learning/images/computational_graph_equation2.jpg)

Se queremos calcular as derivadas de $g$ com respeito a $x$, $y$ e $z$, será muito simples como chamar à função `backward`.

In [52]:
g.backward()

Neste ponto, `Pytorch` a aplicado o algoritmo de `backpropagation` sobre o grafo computacional, calculando todas as derivadas.

$$ \frac{dg}{dz} = p $$

In [53]:
z.grad

tensor(3.)

$$ \frac{dg}{dx} = \frac{dg}{dp} \frac{dp}{dx} = z $$

In [54]:
y.grad

tensor(3.)

Como podemo ver, o `Grafo computacional` é uma ferramenta extraordinária para desenhar REDES NEURAIS de complexidade arbitrária. Com uma simples função, graças ao algoritmo de `backpropagation`, podemos calcular todas as DERIVADAS de maneira simples (cada nodo que representa uma operação só necessita calcular sua própria derivada de maneira local) e otimizar o modelo com nosso algoritmo de Gradiente preferido.

In [ ]:
https://www.youtube.com/watch?v=7sz4WpkUIIs

https://insightlab.ufc.br/tutorial-pytorch-um-guia-rapido-para-voce-entender-agora-os-fundamentos-do-pytorch

https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py
