<h1 align="center">Multi-Target Predictions with Multilinear Regression in PyTorch</h1>

Data Scientist.: Dr.Eddy Giusepe Chirinos Isidro

Link de estudo:

* [Machine Learning Mastery](https://machinelearningmastery.com/multi-target-predictions-with-multilinear-regression-in-pytorch/)

Enquanto nos tutoriais anteriores trabalhamos com regressão multilinear de saída única, aqui exploraremos como podemos usar a regressão multilinear para previsões de vários alvos (`multi-target`). As arquiteturas complexas de redes neurais estão essencialmente fazendo com que cada unidade de neurônio execute a regressão linear independentemente e, em seguida, passe seu resultado para outro neurônio. Portanto, saber como essa regressão funciona é útil para entender como uma rede neural realiza previsões multi alvos (`multi-target`).

O objetivo deste script é fornecer um guia passo a passo para a implementação de previsões de várias target no `PyTorch`. Faremos isso usando a estrutura de um modelo de regressão linear que usa várias features como entrada e produz vários resultados.

Começaremos importando os pacotes necessários para o nosso modelo. Em seguida, definiremos nossos pontos de dados de entrada e o que queremos alcançar com nosso modelo. Particularmente, demonstraremos:

* Como entender a `Regressão Multilinear` em múltiplas dimensões.

* Como fazer previsões `multi-targets` com regressão multilinear no `PyTorch`.

* Como construir uma classe linear usando o `'nn.Module'` no `PyTorch`.

* Como fazer previsões de várias targets (`multi-target`) com uma única amostra de dados de entrada.

* Como fazer previsões de várias targets (`multi-target`) com várias amostras de dados de entrada.

Observe que não vamos treinar `nosso modelo MLR` neste tutorial, veremos apenas como ele faz previsões simples. No tutorial subsequente de nossa série `PyTorch`, aprenderemos como esse modelo pode ser treinado em um conjunto de dados.

# Criamos nosso Módulo

Construiremos uma classe linear personalizada para nosso modelo de `Regressão Multilinear`. Vamos definir uma classe linear e torná-la uma classe filho do pacote `PyTorch nn.Module`. Essa classe herda todos os métodos e atributos do pacote, como `nn.Linear`.

In [1]:
import torch
torch.manual_seed(42)

 
# Define the class for multilinear regression
class MLR(torch.nn.Module):
    def __init__(self, input_dim, output_dim):
        super().__init__()
        self.linear = torch.nn.Linear(input_dim, output_dim)
    
    def forward(self, x):
        y_pred = self.linear(x)
        return y_pred

Agora, vamos criar o objeto modelo e definir os parâmetros de acordo. Como planejamos fazer previsões de `várias targets`, vamos primeiro verificar como nosso modelo funciona para uma única amostra de entrada. Posteriormente, faremos previsões para várias amostras de entrada.

# Fazendo previsões com amostras de entrada única

Criaremos nosso objeto de modelo que recebe uma `única amostra de entrada` e faz cinco previsões.

In [2]:
# Construímos o objeto de nosso Modelo
model = MLR(1, 5)

Agora, vamos definir nosso tensor `x` de entrada para o modelo e fazer previsões.

In [3]:
# Defina a amostra de entrada única 'x' e faça previsões
x = torch.tensor([[2.0]])
y_pred = model(x)
print(y_pred)

tensor([[ 1.7309,  1.1732,  0.1187,  2.7188, -1.1718]],
       grad_fn=<AddmmBackward0>)


Como você pode ver, nosso modelo fez várias previsões a partir de apenas uma única amostra de entrada. Aqui está como podemos listar os parâmetros do modelo.

In [4]:
print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.7645],
        [ 0.8300],
        [-0.2343],
        [ 0.9186],
        [-0.2191]], requires_grad=True), Parameter containing:
tensor([ 0.2018, -0.4869,  0.5873,  0.8815, -0.7336], requires_grad=True)]


Você pode obter um resultado diferente em números, pois esses são pesos aleatórios, mas a forma dos `tensores de peso` corresponderia ao nosso design de **receber uma entrada e fornecer cinco saídas**.

# Fazendo previsões com várias amostras de entrada

Da mesma forma, vamos definir um tensor `X` para várias amostras de entrada, onde cada linha representa uma amostra de dados.

In [5]:
# Define the multiple input tensor 'x' and make predictions
X = torch.tensor([[2.0],[4.0],[6.0]])

Podemos fazer previsões `multi-target` com várias amostras de entrada.

In [6]:
Y_pred = model(X)
print(Y_pred)

tensor([[ 1.7309,  1.1732,  0.1187,  2.7188, -1.1718],
        [ 3.2599,  2.8332, -0.3498,  4.5560, -1.6100],
        [ 4.7890,  4.4932, -0.8184,  6.3932, -2.0482]],
       grad_fn=<AddmmBackward0>)


Juntando tudo, segue o código completo:

In [7]:
import torch
torch.manual_seed(42)
 
# define the class for multilinear regression
class MLR(torch.nn.Module):
    def __init__(self, input_dim, output_dim):
        super().__init__()
        self.linear = torch.nn.Linear(input_dim, output_dim)
    def forward(self,x):
        y_pred = self.linear(x)
        return y_pred
    
# building the model object
model = MLR(1, 5)
 
# define the single input sample 'x' and make predictions
x = torch.tensor([[2.0]])
y_pred = model(x)
print(y_pred)
print(list(model.parameters()))
 
# define the multiple input tensor 'x' and make predictions
X = torch.tensor([[2.0],[4.0],[6.0]])
Y_pred = model(X)
print(Y_pred)

tensor([[ 1.7309,  1.1732,  0.1187,  2.7188, -1.1718]],
       grad_fn=<AddmmBackward0>)
[Parameter containing:
tensor([[ 0.7645],
        [ 0.8300],
        [-0.2343],
        [ 0.9186],
        [-0.2191]], requires_grad=True), Parameter containing:
tensor([ 0.2018, -0.4869,  0.5873,  0.8815, -0.7336], requires_grad=True)]
tensor([[ 1.7309,  1.1732,  0.1187,  2.7188, -1.1718],
        [ 3.2599,  2.8332, -0.3498,  4.5560, -1.6100],
        [ 4.7890,  4.4932, -0.8184,  6.3932, -2.0482]],
       grad_fn=<AddmmBackward0>)
